rules:
  unpinned-uses:
    # c.f. https://docs.zizmor.sh/audits/#unpinned-uses-configuration
    config:
      policies:
        "*": ref-pin

  concurrency-limits:
    ignore:
      - copilot-setup-steps.yml
