---
name: 🐛  Bug Report
description: Create a report to help us improve
labels: ["bug", "needs-triage"]

body:
- type: markdown
  attributes:
    value: >
      **Thank you for wanting to report a bug in pyhf!**


      ⚠
      Verify first that your issue is not [already reported on
      GitHub][issue search].


      [issue search]: https://github.com/scikit-hep/pyhf/issues?q=is%3Aopen+is%3Aissue+label%3Abug

- type: textarea
  attributes:
    label: Summary
    description: Explain the problem briefly below.
    placeholder: >-
      When I try to do X with pyhf and the following workspace, Y breaks or
      Z happens in an unexpected manner.
      Here are all the details I know about this problem.
  validations:
    required: true

- type: textarea
  attributes:
    label: OS / Environment
    description: >-
      Provide information on your operating system.
      Something like the output of `cat /etc/os-release` on Linux or
      `system_profiler -detailLevel mini SPSoftwareDataType` on macOS.
    render: console
    placeholder: |
      # Linux
      $ cat /etc/os-release
      NAME="Ubuntu"
      VERSION="20.04.2 LTS (Focal Fossa)"
      ID=ubuntu
      ID_LIKE=debian
      PRETTY_NAME="Ubuntu 20.04.2 LTS"
      VERSION_ID="20.04"
      HOME_URL="https://www.ubuntu.com/"
      SUPPORT_URL="https://help.ubuntu.com/"
      BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
      PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
      VERSION_CODENAME=focal
      UBUNTU_CODENAME=focal

      # macOS
      $ system_profiler -detailLevel mini SPSoftwareDataType | head -n 6
      Software:

          System Software Overview:

            System Version: macOS 10.15.7 (19H1323)
            Kernel Version: Darwin 19.6.0
  validations:
    required: true

- type: textarea
  attributes:
    label: Steps to Reproduce
    description: >-
      Describe exactly how to reproduce the problem, using a minimal test-case.
      It would *really* help us understand your problem if you paste in the Python code
      that you're running.


      **HINT:** You can paste [GitHub Gist](https://gist.github.com) links for larger files.
    value: |
      <!--- Paste your minimal failing Python example code between the quotes below -->
      ```python (paste below)

      ```

      <!--- ...or if you have a failing CLI command paste it between the quotes below -->
      ```console (paste below)

      ```
  validations:
    required: true

- type: textarea
  attributes:
    label: File Upload (optional)
    description: >-
      If your steps to reproduce your minimal failing example require either a spec or a
      workspace file, please upload it by attaching it to the text area here.


      **HINT:** You can paste [GitHub Gist](https://gist.github.com) links for larger files.
    placeholder: >-
      Attach any files or compressed archives by dragging & dropping, selecting,
      or pasting them here.
  validations:
    required: false

- type: textarea
  attributes:
    label: Expected Results
    description: >-
      Describe what you expected to happen when running the steps above.
    placeholder: >-
      I expected X to happen because I assumed Y.
  validations:
    required: true

- type: textarea
  attributes:
    label: Actual Results
    description: >-
      Paste verbatim program or command output.
      Don't wrap it with tripple backticks &mdash; your whole input will be
      turned into a code snippet automatically.
    render: console
  validations:
    required: true

- type: textarea
  attributes:
    label: pyhf Version
    description: >-
      Paste verbatim output from `pyhf --version` below, under the prompt line.
      Don't wrap it with tripple backticks &mdash; your whole input will be
      turned into a code snippet automatically.
    render: console
    placeholder: |
      $ pyhf --version
  validations:
    required: true

- type: checkboxes
  attributes:
    label: Code of Conduct
    description: |
      Read the [`pyhf` Code of Conduct][CoC] first.

      [CoC]: https://github.com/scikit-hep/pyhf/blob/master/CODE_OF_CONDUCT.md
    options:
    - label: I agree to follow the Code of Conduct
      required: true
...
