name: Publish Docker Images

on:
  push:
    branches:
    - master
    tags:
    - v*
  pull_request:
    branches:
    - master
  workflow_dispatch:

jobs:
  docker:
    name: Build, test, and publish Docker images to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Test build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          repository: pyhf/pyhf
          dockerfile: docker/Dockerfile
          tags: test
          tag_with_sha: true
          tag_with_ref: true
          push: false

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: List built images
        run: docker images

      - name: Run CLI API check
        run: |
          printf "\npyhf\n"
          docker run --rm pyhf/pyhf:test
          printf "\npyhf --version\n"
          docker run --rm pyhf/pyhf:test --version
          printf "\npyhf --help\n"
          docker run --rm pyhf/pyhf:test --help

      - name: Check for curl and tar
        run: >-
          docker run --rm
          --entrypoint /bin/bash
          pyhf/pyhf:test
          -c "which curl; which tar"

      - name: Build and Publish to Registry
        # every PR will trigger a push event on master, so check the push event is actually coming from master
        if: github.event_name == 'push' && github.ref == 'refs/heads/master' && github.repository == 'scikit-hep/pyhf' && "!(startsWith(github.ref, 'refs/tags/'))"
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          repository: pyhf/pyhf
          dockerfile: docker/Dockerfile
          tags: latest
          push: true

      # - name: Build and Publish to Registry with Release Tag
      #   if: startsWith(github.ref, 'refs/tags/')
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     repository: pyhf/pyhf
      #     dockerfile: docker/Dockerfile
      #     tags: latest,latest-stable
      #     push: true
